version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
    openjdk_executor:
        docker:
            - image: circleci/openjdk@sha256:012843a8f91da1ea5e22e142bb5cb8c999a7457e03b8c79ab45d5fcb68043383
        environment:
            _JAVA_OPTIONS: "-Xmx3g"
            GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build_and_test:
    executor:
      name: node/default
    working_directory: /home/circleci/mms
    steps:
      - checkout

      - setup_remote_docker

      - run: 
          name: "Create and start all services from the docker-compose configuration"
          command: |
            cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
            docker-compose up -d
            docker run --network container:mms curlimages/curl --retry 8 --retry-delay 10 --retry-max-time 90 --retry-connrefused http://mms:8080/healthcheck

      - run: 
          name: "Run and test Postman Collection"
          command: |
            cd ~/mms/example
            docker create -v /tst --name mms_test_configs alpine:3.4 /bin/true
            docker cp ~/mms/example/. mms_test_configs:/tst
            docker run --volumes-from mms_test_configs --network container:mms -t postman/newman run /tst/crud.postman_collection.json -e /tst/test-env.json --delay-request 300

      - persist_to_workspace:
            root: /home/circleci/
            paths:
                - mms

  deploy_snapshot:
      executor: openjdk_executor
      steps:
          - attach_workspace:
                at: ~/
          - run:
                name: Deploy snapshot to Artifactory
                command: ./gradlew -PbuildAccess=opensource -PbuildNumber=$CIRCLE_BUILD_NUM -PbuildTag=$CIRCLE_TAG -PartifactoryUrl=$ARTIFACTORY_URL -PartifactoryRepository=$SNAPSHOT_ARTIFACTORY_REPOSITORY -PartifactoryUsername=$ARTIFACTORY_USERNAME -PartifactoryPassword=$ARTIFACTORY_PASSWORD --info --stacktrace artifactoryPublish
  deploy_release:
      executor: openjdk_executor
      steps:
          - attach_workspace:
                at: ~/
          - run:
                name: Deploy release to Artifactory
                command: ./gradlew -PbuildAccess=opensource -PbuildNumber=$CIRCLE_BUILD_NUM -PbuildTag=$CIRCLE_TAG -PartifactoryUrl=$ARTIFACTORY_URL -PartifactoryRepository=$RELEASE_ARTIFACTORY_REPOSITORY -PartifactoryUsername=$ARTIFACTORY_USERNAME -PartifactoryPassword=$ARTIFACTORY_PASSWORD --info --stacktrace artifactoryPublish

workflows:
    version: 2
    build-test-deploy:
      jobs:
        - build_and_test
        - deploy_snapshot:
              requires:
                  - build_and_test
        - deploy_release:
              requires:
                  - build_and_test